[features]
seeds = false
skip-lint = false
[programs.devnet]
solana_ping = "FA51D5fh1VhruC5ZhG2MVvRjfS233QnSD5yEPCbYFd3U"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/brendanmccaffrey/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
